# Generated by Django 3.1.1 on 2020-09-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='msg',
            new_name='feedback',
        ),
    ]
