# Generated by Django 3.1.1 on 2020-09-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200907_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='negative',
            field=models.IntegerField(default=0),
        ),
    ]
