# Generated by Django 3.1.1 on 2020-09-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='diagram',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
