# Generated by Django 3.1.1 on 2020-09-13 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_auto_20200912_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
