# Generated by Django 3.1.1 on 2020-09-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_auto_20200917_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-time']},
        ),
    ]
