# Generated by Django 3.1.1 on 2020-09-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200917_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='diagram',
        ),
        migrations.AddField(
            model_name='report',
            name='attempt',
            field=models.IntegerField(default=1),
        ),
    ]
