# Generated by Django 3.1.1 on 2020-09-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_auto_20200917_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='items',
            field=models.IntegerField(default=0),
        ),
    ]
