# Generated by Django 3.1.1 on 2020-09-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_quiz_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='items',
        ),
    ]
