# Generated by Django 3.1.1 on 2020-09-18 08:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0022_response_attempt'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('quiz', 'student', 'question', 'attempt')},
        ),
    ]
