# Generated by Django 3.1.1 on 2020-09-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20200918_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-score', 'student']},
        ),
    ]
